Repository prgrms-web-devcourse-final-project/WEB4_5_DOD_FE, pull requests merged in 2025-07, with the labels that each got.

#81 [Style] 바텀 시트 높이 차등 적용
  src/app/schedule/[Id]/election/start-point/page.tsx
  src/components/feature/kakaoMap/SubwaySearch.tsx
  src/components/ui/BottomSheet.tsx
  src/components/ui/SubwaySearchResultList.tsx
Labels: 🐛 bug, 🎨 style

#91 [Feat] 일정 페이지 컴포넌트 분리 및 카카오톡 공유 기능 구현
  src/app/schedule/[Id]/page.tsx
  src/components/feature/KakaoScript.tsx
  src/components/feature/WorkSpace.tsx
  src/components/feature/group/MemberParticipationItem.tsx
  src/components/feature/group/WeekdayFrequencyBarChart.tsx
  src/components/feature/schedule/detail/OfflineScheduleDetail.tsx
  src/components/feature/schedule/detail/OnlineScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetailContent.tsx
  src/components/feature/schedule/detail/ScheduleDetailLayout.tsx
  src/components/feature/schedule/edit/workspace/EditWorkspace.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceBottomSheet.tsx
  src/lib/api/groupApi.ts
  src/lib/api/scheduleApi.ts
  src/lib/api/useKakaoShare.ts
  src/types/kakao.d.ts
Labels: ♻️ refactor, ✨ feature, 🎨 style

#92 [Feat] 오프라인 일정 상세 정보 API 연결
  src/app/utils/dateFormat.ts
  src/components/feature/WorkSpace.tsx
  src/components/feature/schedule/detail/OfflineScheduleDetail.tsx
  src/components/feature/schedule/detail/OnlineScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetailContent.tsx
  src/components/feature/schedule/edit/workspace/EditWorkspace.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceBottomSheet.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceItem.tsx
  src/lib/api/scheduleApi.ts
  src/types/schedule.d.ts
Labels: ✨ feature

#95 [Refactor] 그룹 헤더 컴포넌트 분리, Props 추가, 분기 처리에 따른 기능 추가
  src/components/feature/schedule/detail/ScheduleDetailLayout.tsx
  src/components/layout/GroupHeader.tsx
  src/components/layout/GroupHeaderContent.tsx
  src/components/layout/GroupHeaderTop.tsx
  src/components/ui/DropdownSmall.tsx
  src/lib/api/groupApi.ts
Labels: ♻️ refactor, ✨ feature, 🎨 style

#96 [Feat] 웹헤더 - 유저 유무에 따른 헤더 변경 (로그인버튼, 유저프로필 렌더링)
  src/components/layout/Header.tsx
  src/lib/profileImages.ts
Labels: ✨ feature

#97 [Feat] GroupAnalytics 그룹 통계 페이지 구현
  src/app/group/[groupId]/analytics/page.tsx
  src/app/utils/analyticsUtils.ts
  src/assets/images/rabbit_noschedule_sad.png
  src/components/feature/group/analytics/AnalyticsLayout.tsx
  src/components/feature/group/analytics/EmptyGroupAnalytics.tsx
  src/components/feature/group/analytics/EmptyGroupAnalyticsCard.tsx
  src/components/feature/group/analytics/GroupAnalyticsPage.tsx
  src/components/feature/group/analytics/LocationFrequencySection.tsx
  src/components/feature/group/analytics/MemberParticipationSection.tsx
  src/components/feature/group/analytics/WeekdayFrequencySection.tsx
  src/lib/api/groupApi.ts
Labels: ♻️ refactor, ✨ feature, 🎨 style

#98 [Feat] Dashboard, UserSchedule 페이지 API 연결 작업
  src/app/schedule/user/[userId]/page.tsx
  src/app/utils/dateFormat.ts
  src/components/dashboard/Dashboard.tsx
  src/components/dashboard/MyGroupItem.tsx
  src/components/dashboard/MyGroupSection.tsx
  src/components/dashboard/MyScheduleItem.tsx
  src/components/dashboard/MyScheduleSection.tsx
  src/components/dashboard/UserSchedule.tsx
  src/components/dashboard/UserScheduleList.tsx
  src/components/feature/calendar/types.ts
  src/lib/api/dashboardApi.ts
Labels: ♻️ refactor, ✨ feature

#100 [Feat] election start api 연결
  src/app/schedule/[Id]/election/page.tsx
  src/app/schedule/[Id]/election/start/page.tsx
  src/lib/api/ElectionApi.ts
Labels: ✨ feature

#103 [Feat] 그룹 멤버 페이지 구현 및 ControlledAlertBox 구현
  src/app/group/[groupId]/members/page.tsx
  src/assets/icon/crown_icon.svg
  src/components/feature/group/GroupMemberItem.tsx
  src/components/feature/group/detail/GroupHeaderSection.tsx
  src/components/feature/group/members/GroupMembersContent.tsx
  src/components/feature/group/members/GroupMembersPage.tsx
  src/components/feature/group/members/MemberCount.tsx
  src/components/feature/group/members/MemberList.tsx
  src/components/feature/group/members/hooks/useGroupMemberLogic.ts
  src/components/ui/ControlledAlertBox.tsx
  src/lib/api/groupApi.ts
  src/lib/profileImages.ts
Labels: ♻️ refactor, ✨ feature, 🎨 style

#105 [Feat] 오프라인 일정 상세페이지 지도 및 바텀시트 구현
  src/components/feature/MeetingLocation.tsx
  src/components/feature/WorkSpace.tsx
  src/components/feature/schedule/detail/OfflineBottomSheet.tsx
  src/components/feature/schedule/detail/OfflineScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetailContent.tsx
  src/components/layout/BlurredChevronHeader.tsx
  src/components/layout/GroupHeaderContent.tsx
  src/components/layout/GroupHeaderMap.tsx
  src/components/layout/GroupHeaderTop.tsx
  src/components/ui/BottomSheet.tsx
  src/types/schedule.d.ts
Labels: ♻️ refactor, ✨ feature

#107 [Feat] 그룹 생성/수정 관련 API 리팩토링 및 UI 애니메이션 개선
  src/app/group/[groupId]/edit/page.tsx
  src/app/group/[groupId]/schedule/create/select/page.tsx
  src/app/group/create/page.tsx
  src/components/feature/meeting/MeetingTypeChoice.tsx
  src/lib/api/groupApi.ts
  src/types/group.d.ts
Labels: ♻️ refactor, 🎨 style

#108 [Fix] 헤더 - 프로필 렌더링 오류 수정
  src/components/layout/Header.tsx
Labels: 🐛 bug

#110 Feat/election
  src/app/schedule/[Id]/election/wait/page.tsx
  src/components/feature/kakaoMap/SubwaySearch.tsx
Labels: ✨ feature

#112 [Feat] 내 시간표 불러오기 기능 구현
  src/app/meeting/[eventId]/coordinate/[groupId]/page.tsx
  src/components/feature/CommonSchedule.tsx
  src/components/feature/Schedule.tsx
  src/components/feature/meeting/coordinate/ActionMyButton.tsx
  src/components/feature/meeting/coordinate/LoadButton.tsx
  src/components/feature/meeting/coordinate/ScheduleSection.tsx
  src/components/mypage/TimeSheet.tsx
  src/components/ui/AlertBox.tsx
  src/lib/api/scheduleApi.ts
  src/types/schedule.d.ts
Labels: ✨ feature, 🎨 style

#113 [Feat] 그룹 일정 페이지 구현
  src/components/auth/callback/Callback.tsx
  src/components/feature/group/detail/GroupContent.tsx
  src/components/feature/group/detail/GroupDetailPage.tsx
  src/components/feature/group/detail/GroupHeaderSection.tsx
  src/components/feature/group/detail/hooks/useAuthRedirect.ts
  src/components/feature/group/detail/hooks/useGroupDetailLogic.ts
  src/components/feature/group/detail/hooks/useGroupMembership.ts
  src/components/layout/GroupHeader.tsx
  src/components/layout/GroupHeaderContent.tsx
  src/components/layout/GroupHeaderTop.tsx
  src/components/layout/hooks/useGroupHeaderAction.ts
  src/components/ui/ScheduleCard.tsx
  src/lib/api/groupApi.ts
  src/lib/api/scheduleApi.ts
  src/lib/api/useKakaoShare.ts
Labels: ♻️ refactor, ✨ feature, 🎨 style

#114 [Feat] 그룹 멤버 리스트 모션 애니메이션 적용
  src/components/feature/group/members/MemberList.tsx
Labels: ✨ feature, 🎨 style

#115 [Style] 헤더 연결
  src/app/schedule/[Id]/election/start-point/page.tsx
  src/app/schedule/[Id]/election/start/page.tsx
Labels: 🎨 style

#119 [Fix] 마이페이지 시간표 저장 로직 오류 수정
  src/components/feature/Schedule.tsx
  src/components/mypage/TimeSheet.tsx
Labels: 🐛 bug

#120 [Feat] 온라인 일정 페이지 구현 및 일정 시간 변환 및 분류 함수 구현
  src/app/schedule/[Id]/edit/detail/page.tsx
  src/app/schedule/[Id]/edit/workspace/page.tsx
  src/app/utils/analyticsUtils.ts
  src/app/utils/dateFormat.ts
  src/assets/icon/zoom_icon.svg
  src/components/feature/MeetingInfo.tsx
  src/components/feature/OnlineMeetingRoom.tsx
  src/components/feature/WorkSpace.tsx
  src/components/feature/group/analytics/GroupAnalyticsPage.tsx
  src/components/feature/group/analytics/hooks/useGroupAnalyticsData.ts
  src/components/feature/group/detail/GroupContent.tsx
  src/components/feature/group/detail/GroupDetailPage.tsx
  src/components/feature/group/members/hooks/useGroupMemberLogic.ts
  src/components/feature/schedule/detail/OnlineScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetail.tsx
  src/components/feature/schedule/detail/ScheduleDetailContent.tsx
  src/components/feature/schedule/detail/ScheduleDetailLayout.tsx
  src/components/feature/schedule/edit/workspace/EditWorkspace.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceBottomSheet.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceItem.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceSkeletonItem.tsx
  src/components/feature/schedule/edit/workspace/constants/workspace.ts
  src/components/feature/schedule/edit/workspace/hooks/useWorkspaceForm.ts
  src/components/feature/schedule/edit/workspace/hooks/useWorkspaceModal.ts
  src/components/feature/schedule/editSchedule/OnlineMeetingEditBottomSheet.tsx
  src/components/feature/schedule/editSchedule/ScheduleForm.tsx
  src/components/feature/schedule/editSchedule/TimeEditBottomSheet.tsx
  src/components/feature/schedule/editSchedule/TimeSelector.tsx
  src/components/feature/schedule/editSchedule/hooks/useOnlineMeetingForm.ts
  src/components/feature/schedule/hooks/useEditSchedule.ts
  src/components/ui/Dropdown.tsx
  src/components/ui/DropdownSmall.tsx
  src/components/ui/NameTag.tsx
  src/components/ui/ScheduleCard.tsx
  src/lib/api/scheduleApi.ts
  src/lib/api/useKakaoShare.ts
  src/types/schedule.d.ts
Labels: ♻️ refactor, ✨ feature, 🎨 style

#123 [Style] UI 리팩토링 및 그룹 생성 이후 플로우 개선
  src/app/group/[groupId]/complete/page.tsx
  src/app/group/[groupId]/edit/page.tsx
  src/app/group/create/page.tsx
  src/app/not-found.tsx
  src/app/utils/dateFormat.ts
  src/assets/images/404_losthome.png
  src/assets/images/404_not_found.png
  src/assets/images/404_number.png
  src/assets/images/group_created_rabbits.png
  src/components/dashboard/EmptyUserScheduleList.tsx
  src/components/dashboard/LoadUserSchedule.tsx
  src/components/dashboard/LoadUserScheduleList.tsx
  src/components/dashboard/MyGroupSection.tsx
  src/components/dashboard/MyScheduleItem.tsx
  src/components/dashboard/MyScheduleSection.tsx
  src/components/dashboard/Skeleton.tsx
  src/components/dashboard/UserSchedule.tsx
  src/components/dashboard/UserScheduleList.tsx
  src/components/feature/MeetingLocation.tsx
  src/components/feature/WorkSpace.tsx
  src/components/feature/group/analytics/EmptyGroupAnalytics.tsx
  src/components/feature/schedule/detail/OfflineBottomSheet.tsx
  src/components/feature/schedule/detail/OfflineScheduleDetail.tsx
  src/components/feature/schedule/edit/workspace/WorkspaceBottomSheet.tsx
  src/components/feature/schedule/editSchedule/ScheduleForm.tsx
  src/components/layout/GroupHeaderMap.tsx
  src/components/ui/ScheduleCard.tsx
  src/lib/api/dashboardApi.ts
Labels: ♻️ refactor, 🎨 style

#122 [Feat] 일정 확정 구현
  src/app/meeting/[eventId]/coordinate/my/page.tsx
  src/app/meeting/[eventId]/coordinate/page.tsx
  src/app/schedule/create/page.tsx
  src/components/feature/meeting/TimeResult.tsx
  src/components/feature/meeting/TimeResultScheduleCard.tsx
  src/components/feature/meeting/coordinate/CoordinateContent.tsx
  src/components/feature/meeting/coordinate/MySchedule.tsx
  src/components/feature/schedule/ScheduleInfo.tsx
  src/lib/api/scheduleApi.ts
  src/types/schedule.d.ts
Labels: ✨ feature

#126 [Fix] 버그 수정
  src/app/meeting/[eventId]/coordinate/[groupId]/page.tsx
  src/app/meeting/[eventId]/coordinate/page.tsx
  src/app/schedule/[id]/edit/detail/page.tsx
  src/app/schedule/[id]/edit/workspace/layout.tsx
  src/app/schedule/[id]/edit/workspace/page.tsx
  src/app/schedule/[id]/election/page.tsx
  src/app/schedule/[id]/election/result/page.tsx
  src/app/schedule/[id]/election/start-point/page.tsx
  src/app/schedule/[id]/election/start/page.tsx
  src/app/schedule/[id]/election/wait/page.tsx
  src/app/schedule/[id]/page.tsx
  src/app/schedule/complete/[eventId]/page.tsx
  src/app/schedule/create/page.tsx
  src/components/feature/CommonSchedule.tsx
  src/components/feature/Schedule.tsx
  src/components/feature/meeting/TimeResult.tsx
  src/components/feature/meeting/TimeResultScheduleCard.tsx
  src/components/feature/meeting/coordinate/ActionButtons.tsx
  src/components/feature/meeting/coordinate/CoordinateContent.tsx
  src/components/feature/meeting/coordinate/ScheduleSection.tsx
  src/components/feature/meeting/coordinate/TitleWithShare.tsx
  src/components/feature/schedule/ScheduleSelectDate.tsx
  src/lib/api/groupApi.ts
  src/types/kakao.d.ts
Labels: 🐛 bug

#129 [feat] 투표 api 연결
  src/app/schedule/[Id]/election/page.tsx
  src/app/schedule/[Id]/election/result/page.tsx
  src/app/schedule/[Id]/election/start-point/page.tsx
  src/app/schedule/[Id]/election/start/page.tsx
  src/app/schedule/[Id]/election/wait/page.tsx
  src/components/ui/SubwayCard.tsx
  src/lib/api/ElectionApi.ts
  src/types/station.d.ts
Labels: ✨ feature, 🎨 style

#128 [Fix] mypage - 캘린더 ID 삭제 기능 구현 및 아이디 유효성 검사 추가
  src/app/mypage/page.tsx
  src/components/layout/Header.tsx
  src/components/mypage/GoogleCalendarSheet.tsx
  src/components/mypage/ListBox.tsx
  src/components/mypage/NameSheet.tsx
  src/components/mypage/StationSheet.tsx
  src/components/mypage/TimeSheet.tsx
  src/components/ui/AlertBox.tsx
  src/components/ui/LogoWebHeader.tsx
  src/lib/api/authApi.ts
Labels: ✨ feature, 🎨 style

#132 [Fix] 오류 수정
  src/app/schedule/[id]/edit/detail/page.tsx
  src/app/schedule/[id]/edit/workspace/page.tsx
  src/app/schedule/[id]/page.tsx
  src/components/feature/meeting/coordinate/CoordinateContent.tsx
  src/components/feature/schedule/ScheduleSelectDate.tsx
  src/lib/api/scheduleApi.ts
Labels: 🐛 bug

#136 [Fix] 프로필 업데이트 query invalidation 수정
  src/lib/api/authApi.ts
Labels: 🐛 bug

#138 [Feat] Landing 페이지 구성 및 GSAP 애니메이션 적용
  package.json
  src/assets/images/iphone_image.png
  src/assets/images/landing_dashbard.png
  src/assets/images/landing_group_analytics.png
  src/assets/images/landing_group_management.png
  src/assets/images/landing_rabbits.png
  src/assets/images/landing_study_rabbits.png
  src/assets/images/map_rabbits.png
  src/assets/images/timetable_rabbits.png
  src/assets/images/vacation_rabbit.png
  src/assets/images/zoom_rabbits.png
  src/components/landing/Landing.tsx
  src/components/landing/MainLogo.tsx
  src/components/landing/MvpCard.tsx
  src/components/landing/Section1.tsx
  src/components/landing/Section2.tsx
  src/components/landing/Section3.tsx
  src/components/landing/Section4.tsx
  src/components/landing/Section5.tsx
  src/components/landing/Section6.tsx
  src/components/landing/SectionLayout.tsx
  src/components/landing/TextMessage.tsx
Labels: ✨ feature, 🎨 style

#140 [Fix] 일정 확정 값 수정 및 오류 수정
  public/og-image.png
  src/app/layout.tsx
  src/components/feature/meeting/TimeResult.tsx
  src/components/feature/meeting/coordinate/TitleWithShare.tsx
  src/components/feature/schedule/detail/ScheduleDetailContent.tsx
  src/lib/api/scheduleApi.ts
  src/types/schedule.d.ts
Labels: 🐛 bug

#143 [Fix] og 설정 수정
  src/app/layout.tsx
Labels: ♻️ refactor

#142 [Feat] 장소 등록 재진입 예외처리
  src/app/schedule/[id]/election/start-point/page.tsx
  src/components/feature/kakaoMap/SubwaySearch.tsx
  src/lib/api/ElectionApi.ts
  src/types/schedule.d.ts
Labels: ✨ feature

#146 [Feat] 즐겨 찾기 장소 불러오기
  src/app/schedule/[id]/election/page.tsx
  src/app/schedule/[id]/election/start-point/page.tsx
  src/app/schedule/[id]/election/wait/page.tsx
  src/app/utils/getTotalTravelTime.ts
  src/components/feature/kakaoMap/SubwaySearch.tsx
  src/lib/api/ElectionApi.ts
Labels: 🐛 bug, ✨ feature, 🎨 style

#145 [Perf] : 대시보드 - 한달 단위 일정 데이터 캐싱을 통한 성능 개선
  src/app/schedule/[id]/election/page.tsx
  src/app/schedule/[id]/election/start/page.tsx
  src/app/schedule/create/layout.tsx
  src/app/utils/dateFormat.ts
  src/assets/images/schedule_loading_rabbits.png
  src/components/dashboard/Dashboard.tsx
  src/components/feature/group/CreateGroupPage.tsx
  src/components/feature/group/EditGroupPage.tsx
  src/components/feature/meeting/coordinate/ActionMyButton.tsx
  src/components/mypage/TimeSheet.tsx
  src/components/ui/ScheduleRabbit.tsx
  src/lib/api/dashboardApi.ts
  src/lib/api/groupApi.ts
  src/lib/api/scheduleApi.ts
Labels: ♻️ refactor, 🎨 style

#150 [Fix] 마이페이지 - 비로그인 페이지 접근제한 추가 및 장소 api 변수 address 추가
  src/app/mypage/page.tsx
  src/lib/api/authApi.ts
Labels: ✨ feature

#156 Fix: 새로고침시 user 데이터 잠시 못가져올때 로그인 리다이렉트 이동시키는 오류 해결
  src/components/dashboard/LoadUserSchedule.tsx
  src/components/feature/group/EditGroupPage.tsx
  src/components/feature/group/GroupSchdeduleCreateSelectPage.tsx
  src/components/feature/group/analytics/hooks/useGroupAnalyticsData.ts
  src/components/feature/group/members/hooks/useGroupMemberLogic.ts
  src/components/feature/schedule/detail/ScheduleDetail.tsx
  src/components/feature/schedule/edit/workspace/EditWorkspace.tsx
  src/components/feature/schedule/editSchedule/EditScheduleInfoPage.tsx
  src/components/feature/schedule/hooks/useAuthRequired.ts
  src/lib/api/groupApi.ts
Labels: 🐛 bug, ♻️ refactor

#155 [Fix]시간표 기능 추가 및 오류 수정
  src/app/meeting/[eventId]/coordinate/my/page.tsx
  src/app/meeting/[eventId]/coordinate/page.tsx
  src/app/schedule/create/page.tsx
  src/components/auth/login/Login.tsx
  src/components/feature/Schedule.tsx
  src/components/feature/meeting/TimeResult.tsx
  src/components/feature/meeting/coordinate/ActionButtons.tsx
  src/components/feature/meeting/coordinate/MySchedule.tsx
  src/components/feature/meeting/coordinate/ScheduleSection.tsx
  src/lib/api/scheduleApi.ts
  src/lib/api/userApi.ts
Labels: 🐛 bug, ♻️ refactor

#158 [Fix] 시간표 등록시 기존 시간 사라지는 버그 수정
  src/components/feature/Schedule.tsx
Labels: 🐛 bug

#160 Feat/election
  src/components/election/CreateDepartLocationPage.tsx
  src/components/election/ShowMiddleLocationPage.tsx
  src/components/election/StartVotePage.tsx
  src/components/election/VoteMiddleLocationPage.tsx
  src/components/election/WaitingVotePage.tsx
  src/components/feature/kakaoMap/SubwaySearch.tsx
  src/lib/api/ElectionApi.ts
Labels: 🐛 bug, ✨ feature

#161 [Style] 랜딩페이지 Section2 iphone 12pro 및 사이즈 작은 휴대폰 대응 반응형 적용
  src/components/landing/Section2.tsx
  src/components/landing/TextMessage.tsx
Labels: 🎨 style

#162 [Fix] Api 변경으로 인한 온라인 회의장 삭제 request body 변경
  src/components/feature/schedule/editSchedule/hooks/useOnlineMeetingForm.ts
Labels: 🐛 bug, ♻️ refactor

#164 🐛 구글 캘린더 관련 버그 수정
  src/components/dashboard/MyScheduleItem.tsx
  src/components/dashboard/MyScheduleSection.tsx
  src/lib/api/dashboardApi.ts
Labels: 🐛 bug

#169 Fix: 뒤로가기 무한 반복 수정
  src/components/feature/meeting/coordinate/ActionMyButton.tsx
Labels: 🐛 bug

#171 Feat/election
  src/components/election/CreateDepartLocationPage.tsx
  src/components/election/ShowMiddleLocationPage.tsx
  src/components/election/StartVotePage.tsx
  src/components/election/VoteMiddleLocationPage.tsx
  src/components/election/WaitingVotePage.tsx
Labels: 🎨 style
